.<center>
**Course Name:** Deep learning with python<center>
**Assignment Name:** Pandas apply function<center>
**Major:** Computer Science and Technology<center>
**Class:** <center>
**Student Name:** Reeshad Khan<center>
**Student ID:** 2019124921<center>
**Lab:** Computer Room <center> 
**Date:** 2020/05/04 <center>

### Task
Create a DataFrame based on the following data and set the column name to “Stamp”. With the apply function generate the “Year”, “Month”, “Day”, “Hour”, “Minute” and “Second” columns from the “Stamp” column.



2016-12-01 00:00:00

2016-12-01 01:05:10

2016-12-01 02:10:20

2016-12-01 03:15:30

2016-12-01 04:20:40

2016-12-01 05:25:50

2016-12-01 06:30:00

2016-12-01 07:35:10

2016-12-01 08:40:20

2016-12-01 09:45:30

2016-12-01 10:50:40

2016-12-01 11:55:50

In [17]:
import pandas as pd 
# Create date and time with dataframe 
rng = pd.DataFrame() 
rng['stamp'] = pd.date_range('12/1/2016', periods = 72, freq ='3910S') 

# Print the dates in dd-mm-yy format 
rng[:5] 

# Create features for year, month, day, hour, and minute 
rng['year'] = rng['stamp'].dt.year 
rng['month'] = rng['stamp'].dt.month 
rng['day'] = rng['stamp'].dt.day 
rng['hour'] = rng['stamp'].dt.hour 
rng['minute'] = rng['stamp'].dt.minute 
rng['second'] = rng['stamp'].dt.second

# Print the dates divided into features 
rng.head(12)

                 stamp  year  month  day  hour  minute  second
0  2016-12-01 00:00:00  2016     12    1     0       0       0
1  2016-12-01 01:05:10  2016     12    1     1       5      10
2  2016-12-01 02:10:20  2016     12    1     2      10      20
3  2016-12-01 03:15:30  2016     12    1     3      15      30
4  2016-12-01 04:20:40  2016     12    1     4      20      40
5  2016-12-01 05:25:50  2016     12    1     5      25      50
6  2016-12-01 06:31:00  2016     12    1     6      31       0
7  2016-12-01 07:36:10  2016     12    1     7      36      10
8  2016-12-01 08:41:20  2016     12    1     8      41      20
9  2016-12-01 09:46:30  2016     12    1     9      46      30
10 2016-12-01 10:51:40  2016     12    1    10      51      40
11 2016-12-01 11:56:50  2016     12    1    11      56      50